/// Purpose: Generate `lib/shared/utils/chinese_convert_data.dart` from the
/// OpenCC character dictionaries plus the legacy hand-typed table.
/// Inputs: Optional `--commit <sha>`; reads `tool/data/opencc/STCharacters.txt`,
/// `tool/data/opencc/TSCharacters.txt`, and `tool/data/legacy_st_pairs.txt`.
/// Returns: None (exit code 0 on success).
/// Side effects: Overwrites the data file; prints pair counts to stdout.
/// Notes: Deterministic and offline — re-running with unchanged inputs yields
/// an identical file. Simplified→Traditional keeps the legacy choice on a
/// conflict (the legacy table was Taiwan-flavoured: 里→裡, 着→著) and adds
/// every OpenCC key it lacked. Traditional→Simplified takes OpenCC's first
/// value (the many-to-one canonical: 乾/幹→干, 髮/發→发) and falls back to the
/// reversed legacy pairs only for keys OpenCC does not list.
library;

import 'dart:io';

void main(List<String> args) {
  var commit = 'unpinned';
  for (var i = 0; i + 1 < args.length; i++) {
    if (args[i] == '--commit') commit = args[i + 1];
  }
  final st = _readOpenCC('tool/data/opencc/STCharacters.txt');
  final ts = _readOpenCC('tool/data/opencc/TSCharacters.txt');
  final legacy = _readLegacy('tool/data/legacy_st_pairs.txt');

  final s2t = <int, int>{...legacy};
  var added = 0;
  for (final e in st.entries) {
    if (!s2t.containsKey(e.key)) {
      s2t[e.key] = e.value;
      added++;
    }
  }
  final t2s = <int, int>{...ts};
  var addedBack = 0;
  for (final e in legacy.entries) {
    if (!t2s.containsKey(e.value)) {
      t2s[e.value] = e.key;
      addedBack++;
    }
  }

  final out = StringBuffer()
    ..writeln('// GENERATED by tool/gen_chinese_convert.dart — do not edit by hand.')
    ..writeln('//')
    ..writeln('// Derived from OpenCC (https://github.com/BYVoid/OpenCC)')
    ..writeln('// data/dictionary/STCharacters.txt and TSCharacters.txt at commit')
    ..writeln('// $commit, taking the first candidate of each entry, merged with the')
    ..writeln("// app's pre-1.5.7 hand-typed table (tool/data/legacy_st_pairs.txt).")
    ..writeln('//')
    ..writeln('// OpenCC is Copyright (c) Carbo Kuo and contributors and is licensed under')
    ..writeln('// the Apache License, Version 2.0 <http://www.apache.org/licenses/LICENSE-2.0>.')
    ..writeln('// See the in-app license page for the attribution notice.')
    ..writeln()
    ..writeln('/// Interleaved rune pairs: simplified, traditional, simplified, traditional, …')
    ..writeln('const String kSimplifiedToTraditionalPairs =')
    ..write(_literal(s2t))
    ..writeln()
    ..writeln('/// Interleaved rune pairs: traditional, simplified, traditional, simplified, …')
    ..writeln('const String kTraditionalToSimplifiedPairs =')
    ..write(_literal(t2s));
  File('lib/shared/utils/chinese_convert_data.dart').writeAsStringSync(out.toString());
  stdout.writeln(
    'S→T: ${s2t.length} pairs (${legacy.length} legacy + $added from OpenCC); '
    'T→S: ${t2s.length} pairs (${ts.length} from OpenCC + $addedBack legacy-only)',
  );
}

/// Purpose: Read one OpenCC dictionary into a single-rune key→first-value map.
/// Inputs: `path`.
/// Returns: `Map<int, int>` of code points.
/// Side effects: Reads the file.
/// Notes: Skips comments, multi-rune keys or values, and identity mappings.
Map<int, int> _readOpenCC(String path) {
  final map = <int, int>{};
  for (final line in File(path).readAsLinesSync()) {
    if (line.isEmpty || line.startsWith('#')) continue;
    final tab = line.indexOf('\t');
    if (tab < 0) continue;
    final key = line.substring(0, tab).runes.toList();
    final first = line.substring(tab + 1).trim().split(' ').first.runes.toList();
    if (key.length != 1 || first.length != 1 || key[0] == first[0]) continue;
    map.putIfAbsent(key[0], () => first[0]);
  }
  return map;
}

/// Purpose: Read the legacy `简\t繁` pair file.
/// Inputs: `path`.
/// Returns: `Map<int, int>` simplified→traditional.
/// Side effects: Reads the file.
/// Notes: Identity pairs are dropped.
Map<int, int> _readLegacy(String path) {
  final map = <int, int>{};
  for (final line in File(path).readAsLinesSync()) {
    final parts = line.split('\t');
    if (parts.length != 2) continue;
    final k = parts[0].runes.toList();
    final v = parts[1].runes.toList();
    if (k.length != 1 || v.length != 1 || k[0] == v[0]) continue;
    map.putIfAbsent(k[0], () => v[0]);
  }
  return map;
}

/// Purpose: Render a rune map as a sorted, line-wrapped Dart string literal.
/// Inputs: `map`.
/// Returns: The literal text including the trailing `;`.
/// Side effects: None.
/// Notes: Non-BMP runes are written as `\u{XXXXX}` escapes so the file stays
/// safe for tooling that counts UTF-16 units; BMP runes are written literally.
String _literal(Map<int, int> map) {
  final keys = map.keys.toList()..sort();
  final buf = StringBuffer();
  var col = 0;
  buf.write("    '");
  for (final k in keys) {
    for (final r in [k, map[k]!]) {
      final String piece;
      if (r > 0xFFFF) {
        piece = '\\u{${r.toRadixString(16)}}';
      } else if (r == 0x27 || r == 0x5C) {
        piece = r'\' + String.fromCharCode(r);
      } else {
        piece = String.fromCharCode(r);
      }
      buf.write(piece);
      col++;
    }
    if (col >= 64) {
      buf.write("'\n    '");
      col = 0;
    }
  }
  buf.write("';\n");
  return buf.toString();
}
