/// Purpose: Say where an AI result was generated, from the model identity
/// stored with it.
/// Inputs: A model identity such as `modelIdentityOf` returns.
/// Returns: [onlineSourceOf] and [aiGeneratedLabelFor].
/// Side effects: None.
/// Notes: A result stored without an identity counts as on-device: before
/// 1.8.12 recommendation reasons recorded none, and only categories did.
library;

import '../../../l10n/app_localizations.dart';
import 'on_device_ai_service.dart';

/// Purpose: The online source id that generated a result.
/// Inputs: [model], the stored model identity, or null.
/// Returns: The source id (`online:model:…`, or `provider:…` from 1.8.11),
/// or null for an on-device result.
/// Side effects: None.
/// Notes: The identity joins variant and model name with ` · `; both hold
/// the selected source id.
String? onlineSourceOf(String? model) {
  final id = model?.split(' · ').first.trim() ?? '';
  return id.startsWith('online:') || id.startsWith('provider:') ? id : null;
}

/// Purpose: The "generated by" note for a result.
/// Inputs: [l10n]; [model], the stored model identity, or null.
/// Returns: The on-device note, or the online note naming the source.
/// Side effects: Reads the configured sources.
/// Notes: A source removed since keeps the online note without a name.
String aiGeneratedLabelFor(AppLocalizations l10n, String? model) {
  final id = onlineSourceOf(model);
  if (id == null) return l10n.aiGeneratedLabel;
  final name = OnDeviceAiService.sourceBackend.sourceDetail(id);
  return name == null || name.isEmpty
      ? l10n.aiGeneratedOnlineUnknownLabel
      : l10n.aiGeneratedOnlineLabel(name);
}
