/// Purpose: Say where an AI result was generated, from the model identity
/// stored with it.
/// Inputs: A model identity such as `modelIdentityOf` returns.
/// Returns: [onlineProviderOf] and [aiGeneratedLabelFor].
/// Side effects: None.
/// Notes: A result stored without an identity counts as on-device: before
/// 1.8.12 recommendation reasons recorded none, and only categories did.
library;

import '../../../l10n/app_localizations.dart';
import 'on_device_ai_service.dart';

/// Purpose: The online provider that generated a result.
/// Inputs: [model], the stored model identity, or null.
/// Returns: The provider id (`provider:…`), or null for an on-device result.
/// Side effects: None.
/// Notes: Online selections are stored as `provider:<id>`; the identity joins
/// variant and model name with ` · `, so the id may appear twice.
String? onlineProviderOf(String? model) =>
    RegExp(r'provider:[^\s·|]+').firstMatch(model ?? '')?.group(0);

/// Purpose: The "generated by" note for a result.
/// Inputs: [l10n]; [model], the stored model identity, or null.
/// Returns: The on-device note, or the online note naming the provider.
/// Side effects: Reads the configured providers.
/// Notes: A provider removed since keeps the online note without a name.
String aiGeneratedLabelFor(AppLocalizations l10n, String? model) {
  final id = onlineProviderOf(model);
  if (id == null) return l10n.aiGeneratedLabel;
  final name = OnDeviceAiService.sourceBackend.online.providers
      .where((p) => p.id == id)
      .firstOrNull
      ?.name;
  return name == null || name.isEmpty
      ? l10n.aiGeneratedOnlineUnknownLabel
      : l10n.aiGeneratedOnlineLabel(name);
}
